apiVersion: apps/v1
kind: Deployment
metadata:
  name: banking-app-deploy
  labels:
    app: banking-app-deploy-lbl
spec:
  replicas: 3
  selector:
    matchLabels:
      app: banking-app
  template:
    metadata:
      labels:
        app: banking-app
    spec:
      containers:
      - name: banking-app-container
        image: sweta912sharma/banking-app
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: banking-app-np-service
  labels:
    app: banking-app
spec:
  selector:
    app: banking-app-deploy-lbl

  type: NodePort
  ports:
  - nodePort: 31028
    port: 8080
    targetPort: 8080
